name: CI for Dockerized Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:$GITHUB_SHA .
          docker tag my-app:$GITHUB_SHA my-docker-repo/my-app:$GITHUB_SHA
        
      # - name: Push Docker image
      #   run: |
      #     docker push my-docker-repo/my-app:$GITHUB_SHA
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
