name: CI for Dockerized Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # **Step 1: Run Trivy vulnerability scanner (Repository Scan)**
      - name: Run Trivy vulnerability scanner (Repository Scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'  # Scans the entire repository
          ignore-unfixed: true  # Ignore vulnerabilities that don’t have a fix yet
          severity: 'CRITICAL,HIGH'  # Report only critical and high vulnerabilities

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # **Step 2: Build Docker image**
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$GITHUB_SHA .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$GITHUB_SHA ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      # **Step 3: Log in to GitHub Container Registry**
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # **Step 4: Push Docker image**
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
      
      # **Step 5: Dockle scan 
      - name: Run Dockle Container Image Security Scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock goodwithtech/dockle:latest \
            --exit-code 1 \  # 🚨 This makes the build fail on security issues
            --accept-key CIS-DI-0010,CIS-DI-0005,CIS-DI-0001 \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$GITHUB_SHA
        